version: '3.8'

services:
  app:
    build: .
    container_name: php_app
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: php_nginx
    restart: always
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: php_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  postgres:
#    image: postgres:15
#    container_name: postgres_db
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./public/app
      dockerfile: Dockerfile
    container_name: vite_frontend
    restart: always
    ports:
      - "9001:80"
    depends_on:
      - app

volumes:
  mysql_data:
